# Generated by Django 5.2.17 on 2026-08-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
