# Generated by Django 5.2.17 on 2026-08-31 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField(blank=True)),
                ('bolsa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carga_horaria', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('ENCERRADA', 'Encerrada')], default='PENDENTE', max_length=20)),
                ('data_publicacao', models.DateTimeField(blank=True, null=True)),
                ('data_encerramento', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vagas.curso')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vagas.empresa')),
            ],
        ),
    ]
