# Generated by Django 5.2.17 on 2026-08-31 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0005_vaga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em análise'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vagas.aluno')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vagas.vaga')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('aluno', 'vaga'), name='candidatura_unica_aluno_vaga')],
            },
        ),
    ]
