# Generated by Django 5.2.17 on 2026-09-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0008_empresa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='curriculos/'),
        ),
    ]
