# Generated by Django 5.2.17 on 2026-09-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0009_aluno_curriculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='senha_provisoria',
            field=models.BooleanField(default=True),
        ),
    ]
