# Generated by Django 5.2.17 on 2026-09-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0010_aluno_senha_provisoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='senha_provisoria',
            field=models.BooleanField(default=True),
        ),
    ]
