
# Generated by Django 5.2.17 on 2026-10-09 21:32

import django.db.models.deletion
from django.db import migrations, models


def copiar_cursos_antigos(apps, schema_editor):
    Vaga = apps.get_model('vagas', 'Vaga')
    banco = schema_editor.connection.alias

    for vaga in Vaga.objects.using(banco).all().iterator():
        if vaga.curso_id:
            vaga.cursos.add(vaga.curso_id)


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0011_empresa_senha_provisoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='cursos',
            field=models.ManyToManyField(
                blank=True,
                related_name='vagas',
                to='vagas.curso',
            ),
        ),
        migrations.RunPython(
            copiar_cursos_antigos,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='vaga',
            name='curso',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='vagas.curso',
            ),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDENTE', 'Aguardando análise'),
                    ('APROVADA', 'Em aberto'),
                    ('REJEITADA', 'Rejeitada'),
                    ('ENCERRADA', 'Encerrada'),
                ],
                default='PENDENTE',
                max_length=20,
            ),
        ),
    ]
